name = "proxy"
main = "src/index.ts"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  # { pattern = "your-domain.example.com", custom_domain = true }  # 可选:自定义域名
]

# KV：面板配置存储
[[kv_namespaces]]
binding = "KV"
id = "314b603009c74d67995937477c8e603a"

[observability]
enabled = true
